import textwrap

from typing import cast, override, TYPE_CHECKING

from typer.models import OptionInfo

from RepoAuditorWeb.lib.dynamic_parameters import TyperParameter
from RepoAuditorWeb.lib.requirement import EvaluateResult, EvaluateResultValue, Requirement

if TYPE_CHECKING:
    from RepoAuditorWeb.lib.module import Module
    from RepoAuditorWeb.lib.plugins.github_impl.module import GitHubSession


# The rule type reported by the branch rules endpoint for GitHub's "Restrict updates" rule.
RULE_TYPE = "update"


# ----------------------------------------------------------------------
class RestrictUpdatesRequirement(Requirement):
    """Validates whether a ruleset restricts pushes to branches matching its pattern, so that only those with bypass permissions can update them."""

    # ----------------------------------------------------------------------
    def __init__(self) -> None:
        super().__init__(
            "RestrictUpdates",
            cast(str, self.__class__.__doc__),
        )

    # ----------------------------------------------------------------------
    @override
    def _GetParametersImpl(self) -> dict[str, TyperParameter]:
        return {
            "require": TyperParameter(
                bool,
                False,  # noqa: FBT003
                OptionInfo(help="Require that updates are restricted."),
            ),
        }

    # ----------------------------------------------------------------------
    @override
    def _EvaluateImpl(
        self,
        module: Module,
        query_data: dict[str, object],
        requirement_data: dict[str, object],
    ) -> EvaluateResult:
        rules = cast(list[dict[str, object]], query_data["response"])
        restrict_updates_value = any(rule.get("type") == RULE_TYPE for rule in rules)

        acceptable_value = cast(bool, requirement_data["require"])

        rationale = textwrap.dedent(
            """\
            The default behavior is to require that a ruleset does not restrict updates, which
            matches GitHub's own default when a branch ruleset is created.

            ## Reasons for this Default

            - The rule blocks every update to the branch rather than screening what an update
              contains. A merge that passed review and every required status check is refused on the
              same grounds as an unreviewed direct push, so the branch stops accepting the work that
              the rest of the ruleset exists to admit.
            - Pull request merges are pushes. Enabling this rule on a branch that receives merges
              presents contributors with a merge button blocked by "The base branch does not allow
              updates", which describes the branch rather than anything the contributor can correct.
            - The protections that govern how a branch advances are already expressed by other
              rules. Requiring a pull request, requiring status checks, and blocking force pushes
              constrain the content and provenance of an update while still allowing sanctioned work
              to land; this rule substitutes an unconditional refusal for that judgment.
            - Bypass permission becomes the only route by which the branch can move forward, so
              routine merges are performed as bypasses. This converts the bypass list from an
              exception path into the normal one, and the audit record it produces no longer
              distinguishes ordinary work from an override.

            ## Reasons to Override this Default

            - The branch is a published snapshot that is meant to be immutable once written, such as
              a tag-like release branch, a `gh-pages` branch generated by a workflow, or a branch
              retained as an audit record.
            - The repository is an archive or a mirror whose contents are written by a single
              synchronizing actor holding bypass permission, where any other push represents
              divergence from the upstream source.

            Note that this rule restricts who may push to a matching branch rather than freezing it
            outright. Anyone named in the ruleset's bypass list may still update it, as may a
            repository administrator when the ruleset grants administrators bypass.
            """,
        )

        if restrict_updates_value != acceptable_value:
            repository_url = cast("GitHubSession", query_data["session"]).github_url
            branch_name = cast(str, query_data["branch"])

            action = "Check" if acceptable_value else "Clear"

            resolution = textwrap.dedent(
                f"""\
                1) Open the repository's [Rules settings]({repository_url}/settings/rules) page.
                2) Click the name of the ruleset that targets `{branch_name}`.
                3) {action} the **Restrict updates** checkbox in the **Branch rules** section.
                4) Click the **Save changes** button at the bottom of the page.

                See [Available rules for rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/available-rules-for-rulesets#restrict-updates)
                for more information.
                """,
            )

            return EvaluateResult(
                EvaluateResultValue.Error,
                f"The repository's value is '{restrict_updates_value}', but the requirement specifies it must be '{acceptable_value}'.",
                resolution,
                rationale,
                self,
                module,
            )

        return EvaluateResult(EvaluateResultValue.Success, None, None, rationale, self, module)
