import textwrap

import pytest

from RepoAuditorWeb.lib.plugins.github_impl.standard_requirements.secret_push_protection import (
    SecretPushProtectionRequirement,
)
from RepoAuditorWeb.lib.plugins.github_impl.module import GitHubSession
from RepoAuditorWeb.lib.requirement import EvaluateResult, EvaluateResultValue

from conftest import MyModule, MyQuery


# ----------------------------------------------------------------------
_DOCUMENTATION_URL = "https://docs.github.com/en/code-security/secret-scanning/enabling-secret-scanning-features/enabling-push-protection-for-your-repository"


# ----------------------------------------------------------------------
_RATIONALE = textwrap.dedent(
    """\
    The default behavior is to require that push protection is enabled.

    ## Reasons for this Default

    - Secret protection reports a credential that has already been disclosed; push
      protection rejects the push that would have disclosed it. The credential that never
      reached the repository is the one that does not have to be rotated, which is the
      entire difference between the two settings.
    - A credential is exposed at the moment of the push, not at the moment someone notices.
      Removing the line afterwards does not undo the disclosure, because the commit that
      introduced it remains reachable and may already have been fetched, so the only
      remedy left is revoking the credential.
    - The check runs against the same partner patterns that secret protection already
      detects, so a repository with secret protection enabled gains no new class of false
      positive by also blocking on them; it acts on the detections it was going to make
      anyway.
    - The block is not absolute. Anyone with write access can push regardless by stating a
      reason, so the setting costs a deliberate override rather than preventing legitimate
      work, and the override is recorded in an alert and the audit log rather than passing
      silently.
    - The feedback arrives at the moment the credential is introduced and names the file
      and the secret type, which is when the author still has the context to replace it
      with a reference to a secret store.

    ## Reasons to Override this Default

    - The repository intentionally contains strings that match supported patterns, such as
      test fixtures, documentation examples, or revoked sample keys, and blocking every
      push that touches them makes routine work depend on the bypass flow. Excluding paths
      with `secret_scanning.yml` is the narrower alternative to disabling the setting.
    - Pushes are generated by automation that cannot respond to a block or supply a bypass
      reason, in which case a rejected push presents as an unexplained failure rather than
      as a credential to fix.
    - The repository is private and the organization does not hold the GitHub Secret
      Protection license the setting requires there, in which case enabling it is a
      purchasing decision rather than a configuration one.

    Note that the setting depends on secret protection, so enabling it on a repository
    where secret protection is disabled requires enabling that setting first.

    Note also that only a subset of the supported patterns is eligible for push protection,
    so the setting reduces the number of credentials that reach the repository without
    establishing that none can.
    """,
)


# ----------------------------------------------------------------------
def _CreateResponse(status: str) -> dict:
    return {"security_and_analysis": {"secret_scanning_push_protection": {"status": status}}}


# ----------------------------------------------------------------------
def _CreateModule(requirement: SecretPushProtectionRequirement) -> MyModule:
    return MyModule("MyModule", "My description.", [MyQuery("MyQuery", [requirement])])


# ----------------------------------------------------------------------
def _Evaluate(
    response: dict,
    *,
    disallow: bool = False,
    url: str = "https://github.com/gt-csse/RepoAuditorWeb",
    pat: str | None = "my-pat",
) -> EvaluateResult:
    requirement = SecretPushProtectionRequirement()

    return requirement.Evaluate(
        _CreateModule(requirement),
        {"response": response, "session": GitHubSession(url, pat)},
        {"skip": False, "disallow": disallow},
    )


# ----------------------------------------------------------------------
def test_Construct():
    requirement = SecretPushProtectionRequirement()

    assert requirement.name == "SecretPushProtection"
    assert (
        requirement.description
        == "Validates whether GitHub rejects a push that introduces a recognized credential, before the credential reaches the repository."
    )
    assert requirement.requires_explicit_include is False


# ----------------------------------------------------------------------
def test_GetParameters():
    parameters = SecretPushProtectionRequirement().GetParameters()

    assert list(parameters.keys()) == ["skip", "disallow"]
    assert parameters["disallow"].type is bool
    assert parameters["disallow"].default is False


# ----------------------------------------------------------------------
@pytest.mark.parametrize(
    ("status", "disallow"),
    [("enabled", False), ("disabled", True)],
)
def test_MatchingStatus(status, disallow):
    result = _Evaluate(_CreateResponse(status), disallow=disallow)

    assert result.result == EvaluateResultValue.Success
    assert result.context is None
    assert result.resolution is None


# ----------------------------------------------------------------------
# The rationale explains the default regardless of the outcome, so it is present on success even
# though there is nothing to resolve.
def test_SuccessRationale():
    result = _Evaluate(_CreateResponse("enabled"))

    assert result.rationale == _RATIONALE


# ----------------------------------------------------------------------
def test_ErrorRationale():
    result = _Evaluate(_CreateResponse("disabled"))

    assert result.rationale == _RATIONALE


# ----------------------------------------------------------------------
def test_ErrorResolution():
    result = _Evaluate(_CreateResponse("disabled"))

    assert result.resolution == textwrap.dedent(
        f"""\
        1) Open the repository's [Advanced Security settings](https://github.com/gt-csse/RepoAuditorWeb/settings/security_analysis) page.
        2) Scroll to the **Secret Protection** section.
        3) Click the **Enable** button next to **Push protection**.
        4) Click the **Save changes** button at the bottom of the page.

        See [Enabling push protection for your repository]({_DOCUMENTATION_URL})
        for more information.
        """,
    )


# ----------------------------------------------------------------------
# The resolution directs the user to disable the setting when push protection must not be enabled.
def test_ErrorResolutionWhenDisallowed():
    result = _Evaluate(_CreateResponse("enabled"), disallow=True)

    assert result.resolution == textwrap.dedent(
        f"""\
        1) Open the repository's [Advanced Security settings](https://github.com/gt-csse/RepoAuditorWeb/settings/security_analysis) page.
        2) Scroll to the **Secret Protection** section.
        3) Click the **Disable** button next to **Push protection**.
        4) Click the **Save changes** button at the bottom of the page.

        See [Enabling push protection for your repository]({_DOCUMENTATION_URL})
        for more information.
        """,
    )


# ----------------------------------------------------------------------
# The settings url is derived from the repository under audit rather than hard-coded, so it points
# at an Enterprise host when one is being audited.
def test_ResolutionUsesEnterpriseUrl():
    result = _Evaluate(
        _CreateResponse("disabled"),
        url="https://github.example.com/my-org/my-repo",
    )

    assert result.resolution is not None
    assert "(https://github.example.com/my-org/my-repo/settings/security_analysis)" in result.resolution


# ----------------------------------------------------------------------
def test_DisabledWhenRequired():
    result = _Evaluate(_CreateResponse("disabled"))

    assert result.result == EvaluateResultValue.Error
    assert result.context == (
        "The repository's value is 'False', but the requirement specifies it must be 'True'."
    )


# ----------------------------------------------------------------------
def test_EnabledWhenDisallowed():
    result = _Evaluate(_CreateResponse("enabled"), disallow=True)

    assert result.result == EvaluateResultValue.Error
    assert result.context == (
        "The repository's value is 'True', but the requirement specifies it must be 'False'."
    )


# ----------------------------------------------------------------------
# An explicit 'disabled' is a visible setting that is genuinely off, so it fails rather than being
# treated as the unknown case.
def test_DisabledIsDistinctFromUnknown():
    result = _Evaluate(_CreateResponse("disabled"), pat=None)

    assert result.result == EvaluateResultValue.Error
    assert result.context == (
        "The repository's value is 'False', but the requirement specifies it must be 'True'."
    )


# ----------------------------------------------------------------------
# GitHub omits the security and analysis settings for a caller without admin access, so an absent
# value means the setting is unknown rather than disabled. A missing token is the user's to
# correct, so it warns.
@pytest.mark.parametrize(
    "response",
    [
        {},
        {"security_and_analysis": None},
        {"security_and_analysis": {}},
    ],
)
def test_MissingStatusWithoutPat(response):
    result = _Evaluate(response, pat=None)

    assert result.result == EvaluateResultValue.Warning
    assert result.context == (
        "The repository's security and analysis settings are not visible because a Personal Access Token was not provided."
    )


# ----------------------------------------------------------------------
# The resolution comes from the shared helper, which explains how to supply a token.
def test_MissingStatusWithoutPatResolution():
    result = _Evaluate({}, pat=None)

    assert result.resolution is not None
    assert "`--GitHub-pat`" in result.resolution


# ----------------------------------------------------------------------
# The setting requires admin access rather than the push access that the other restricted settings
# require, so the resolution asks for admin access.
def test_MissingStatusWithPat():
    result = _Evaluate({})

    assert result.result == EvaluateResultValue.Error
    assert result.context == (
        "The repository's security and analysis settings are not visible because the Personal Access Token provided does not grant admin access to the repository."
    )


# ----------------------------------------------------------------------
# The setting cannot be evaluated when it is not visible, so 'disallow' does not turn an unknown
# value into a passing result.
@pytest.mark.parametrize(
    ("pat", "expected_result"),
    [
        (None, EvaluateResultValue.Warning),
        ("my-pat", EvaluateResultValue.Error),
    ],
)
def test_MissingStatusWhenDisallowed(pat, expected_result):
    result = _Evaluate({}, disallow=True, pat=pat)

    assert result.result == expected_result


# ----------------------------------------------------------------------
# The rationale explains a default that could not be evaluated, so it is omitted when the setting is
# not visible; the problem is the token rather than the repository's configuration.
@pytest.mark.parametrize("pat", [None, "my-pat"])
def test_MissingStatusHasNoRationale(pat):
    result = _Evaluate({}, pat=pat)

    assert result.rationale is None


# ----------------------------------------------------------------------
# Push protection is a distinct setting from the secret protection it depends on, so a response that
# reports only secret protection is treated as though the value is not visible.
def test_SecretScanningStatusIsNotUsed():
    result = _Evaluate({"security_and_analysis": {"secret_scanning": {"status": "enabled"}}})

    assert result.result == EvaluateResultValue.Error
    assert result.context == (
        "The repository's security and analysis settings are not visible because the Personal Access Token provided does not grant admin access to the repository."
    )


# ----------------------------------------------------------------------
def test_Skip():
    requirement = SecretPushProtectionRequirement()

    result = requirement.Evaluate(_CreateModule(requirement), {}, {"skip": True, "disallow": False})

    assert result.result == EvaluateResultValue.Skipped
