import textwrap

from typing import cast, override, TYPE_CHECKING

from typer.models import OptionInfo

from RepoAuditorWeb.lib.dynamic_parameters import TyperParameter
from RepoAuditorWeb.lib.plugins.github_impl.standard_requirements.restricted_value import (
    AccessLevel,
    ENABLED_STATUS,
    GetRestrictedValue,
)
from RepoAuditorWeb.lib.requirement import EvaluateResult, EvaluateResultValue, Requirement

if TYPE_CHECKING:
    from RepoAuditorWeb.lib.module import Module
    from RepoAuditorWeb.lib.plugins.github_impl.module import GitHubSession


# ----------------------------------------------------------------------
class SecretPushProtectionRequirement(Requirement):
    """Validates whether GitHub rejects a push that introduces a recognized credential, before the credential reaches the repository."""

    # ----------------------------------------------------------------------
    def __init__(self) -> None:
        super().__init__(
            "SecretPushProtection",
            cast(str, self.__class__.__doc__),
        )

    # ----------------------------------------------------------------------
    @override
    def _GetParametersImpl(self) -> dict[str, TyperParameter]:
        return {
            # The default requires the setting to be enabled, so the parameter names the override
            # rather than the default; a 'require' parameter defaulting to True would be a flag that
            # is already on and cannot be turned off.
            "disallow": TyperParameter(
                bool,
                False,  # noqa: FBT003
                OptionInfo(help="Require that push protection is not enabled."),
            ),
        }

    # ----------------------------------------------------------------------
    @override
    def _EvaluateImpl(
        self,
        module: Module,
        query_data: dict[str, object],
        requirement_data: dict[str, object],
    ) -> EvaluateResult:
        acceptable_value = not cast(bool, requirement_data["disallow"])

        rationale = textwrap.dedent(
            """\
            The default behavior is to require that push protection is enabled.

            ## Reasons for this Default

            - Secret protection reports a credential that has already been disclosed; push
              protection rejects the push that would have disclosed it. The credential that never
              reached the repository is the one that does not have to be rotated, which is the
              entire difference between the two settings.
            - A credential is exposed at the moment of the push, not at the moment someone notices.
              Removing the line afterwards does not undo the disclosure, because the commit that
              introduced it remains reachable and may already have been fetched, so the only
              remedy left is revoking the credential.
            - The check runs against the same partner patterns that secret protection already
              detects, so a repository with secret protection enabled gains no new class of false
              positive by also blocking on them; it acts on the detections it was going to make
              anyway.
            - The block is not absolute. Anyone with write access can push regardless by stating a
              reason, so the setting costs a deliberate override rather than preventing legitimate
              work, and the override is recorded in an alert and the audit log rather than passing
              silently.
            - The feedback arrives at the moment the credential is introduced and names the file
              and the secret type, which is when the author still has the context to replace it
              with a reference to a secret store.

            ## Reasons to Override this Default

            - The repository intentionally contains strings that match supported patterns, such as
              test fixtures, documentation examples, or revoked sample keys, and blocking every
              push that touches them makes routine work depend on the bypass flow. Excluding paths
              with `secret_scanning.yml` is the narrower alternative to disabling the setting.
            - Pushes are generated by automation that cannot respond to a block or supply a bypass
              reason, in which case a rejected push presents as an unexplained failure rather than
              as a credential to fix.
            - The repository is private and the organization does not hold the GitHub Secret
              Protection license the setting requires there, in which case enabling it is a
              purchasing decision rather than a configuration one.

            Note that the setting depends on secret protection, so enabling it on a repository
            where secret protection is disabled requires enabling that setting first.

            Note also that only a subset of the supported patterns is eligible for push protection,
            so the setting reduces the number of credentials that reach the repository without
            establishing that none can.
            """,
        )

        # Unlike the other restricted settings, 'security_and_analysis' requires admin access rather
        # than push access, and reports the setting as a nested status string rather than a boolean.
        status_value = GetRestrictedValue(
            module,
            self,
            query_data,
            ("security_and_analysis", "secret_scanning_push_protection", "status"),
            "security and analysis settings",
            AccessLevel.Admin,
        )

        if isinstance(status_value, EvaluateResult):
            return status_value

        secret_push_protection_value = status_value == ENABLED_STATUS

        if secret_push_protection_value != acceptable_value:
            action = "Enable" if acceptable_value else "Disable"

            repository_url = cast("GitHubSession", query_data["session"]).github_url

            resolution = textwrap.dedent(
                f"""\
                1) Open the repository's [Advanced Security settings]({repository_url}/settings/security_analysis) page.
                2) Scroll to the **Secret Protection** section.
                3) Click the **{action}** button next to **Push protection**.
                4) Click the **Save changes** button at the bottom of the page.

                See [Enabling push protection for your repository](https://docs.github.com/en/code-security/secret-scanning/enabling-secret-scanning-features/enabling-push-protection-for-your-repository)
                for more information.
                """,
            )

            return EvaluateResult(
                EvaluateResultValue.Error,
                f"The repository's value is '{secret_push_protection_value}', but the requirement specifies it must be '{acceptable_value}'.",
                resolution,
                rationale,
                self,
                module,
            )

        return EvaluateResult(EvaluateResultValue.Success, None, None, rationale, self, module)
