import textwrap

import pytest

from RepoAuditorWeb.lib.plugins.github_impl.module import GitHubSession
from RepoAuditorWeb.lib.plugins.github_impl.ruleset_requirements.restrict_updates import (
    RestrictUpdatesRequirement,
)
from RepoAuditorWeb.lib.requirement import EvaluateResult, EvaluateResultValue

from conftest import MyModule, MyQuery


# ----------------------------------------------------------------------
_DOCUMENTATION_URL = (
    "https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository"
    "/managing-rulesets/available-rules-for-rulesets#restrict-updates"
)


# ----------------------------------------------------------------------
_RATIONALE = textwrap.dedent(
    """\
    The default behavior is to require that a ruleset does not restrict updates, which
    matches GitHub's own default when a branch ruleset is created.

    ## Reasons for this Default

    - The rule blocks every update to the branch rather than screening what an update
      contains. A merge that passed review and every required status check is refused on the
      same grounds as an unreviewed direct push, so the branch stops accepting the work that
      the rest of the ruleset exists to admit.
    - Pull request merges are pushes. Enabling this rule on a branch that receives merges
      presents contributors with a merge button blocked by "The base branch does not allow
      updates", which describes the branch rather than anything the contributor can correct.
    - The protections that govern how a branch advances are already expressed by other
      rules. Requiring a pull request, mandating status checks, and blocking force pushes
      constrain the content and provenance of an update while still allowing sanctioned work
      to land; this rule substitutes an unconditional refusal for that judgment.
    - Bypass permission becomes the only route by which the branch can move forward, so
      routine merges are performed as bypasses. This converts the bypass list from an
      exception path into the normal one, and the audit record it produces no longer
      distinguishes ordinary work from an override.

    ## Reasons to Override this Default

    - The branch is a published snapshot that is meant to be immutable once written, such as
      a tag-like release branch, a `gh-pages` branch generated by a workflow, or a branch
      retained as an audit record.
    - The repository is an archive or a mirror whose contents are written by a single
      synchronizing actor holding bypass permission, where any other push represents
      divergence from the upstream source.

    Note that this rule restricts who may push to a matching branch rather than freezing it
    outright. Anyone named in the ruleset's bypass list may still update it, as may a
    repository administrator when the ruleset grants administrators bypass.
    """,
)


# ----------------------------------------------------------------------
_UPDATE_RULE = {
    "type": "update",
    "ruleset_source_type": "Repository",
    "ruleset_source": "gt-csse/RepoAuditorWeb",
    "ruleset_id": 42,
    "parameters": {"update_allows_fetch_and_merge": False},
}

_OTHER_RULE = {
    "type": "deletion",
    "ruleset_source_type": "Repository",
    "ruleset_source": "gt-csse/RepoAuditorWeb",
    "ruleset_id": 42,
    "parameters": {},
}


# ----------------------------------------------------------------------
def _CreateModule(requirement: RestrictUpdatesRequirement) -> MyModule:
    return MyModule("MyModule", "My description.", [MyQuery("MyQuery", [requirement])])


# ----------------------------------------------------------------------
def _Evaluate(
    response: list[dict],
    *,
    require: bool = False,
    branch: str = "main",
    url: str = "https://github.com/gt-csse/RepoAuditorWeb",
) -> EvaluateResult:
    requirement = RestrictUpdatesRequirement()

    return requirement.Evaluate(
        _CreateModule(requirement),
        {
            "response": response,
            "branch": branch,
            "session": GitHubSession(url, "my-pat"),
        },
        {"skip": False, "require": require},
    )


# ----------------------------------------------------------------------
def test_Construct():
    requirement = RestrictUpdatesRequirement()

    assert requirement.name == "RestrictUpdates"
    assert (
        requirement.description
        == "Validates whether a ruleset restricts pushes to branches matching its pattern, so that only those with bypass permissions can update them."
    )
    assert requirement.requires_explicit_include is False


# ----------------------------------------------------------------------
def test_GetParameters():
    parameters = RestrictUpdatesRequirement().GetParameters()

    assert list(parameters.keys()) == ["skip", "require"]
    assert parameters["require"].type is bool
    assert parameters["require"].default is False


# ----------------------------------------------------------------------
@pytest.mark.parametrize(
    ("response", "require"),
    [
        ([], False),
        ([_OTHER_RULE], False),
        ([_UPDATE_RULE], True),
        ([_OTHER_RULE, _UPDATE_RULE], True),
    ],
)
def test_MatchingValue(response, require):
    result = _Evaluate(response, require=require)

    assert result.result == EvaluateResultValue.Success
    assert result.context is None
    assert result.resolution is None


# ----------------------------------------------------------------------
# The rationale explains the default regardless of the outcome, so it is present on success even
# though there is nothing to resolve.
@pytest.mark.parametrize("response", [[_UPDATE_RULE], [_OTHER_RULE]])
def test_Rationale(response):
    result = _Evaluate(response)

    assert result.rationale == _RATIONALE


# ----------------------------------------------------------------------
def test_RestrictedWhenNotRequired():
    result = _Evaluate([_UPDATE_RULE])

    assert result.result == EvaluateResultValue.Error
    assert result.context == (
        "The repository's value is 'True', but the requirement specifies it must be 'False'."
    )


# ----------------------------------------------------------------------
# The endpoint reports only the rules that apply, so a branch whose rules do not include the update
# rule is one whose pushes are unrestricted.
@pytest.mark.parametrize("response", [[], [_OTHER_RULE]])
def test_UnrestrictedWhenRequired(response):
    result = _Evaluate(response, require=True)

    assert result.result == EvaluateResultValue.Error
    assert result.context == (
        "The repository's value is 'False', but the requirement specifies it must be 'True'."
    )


# ----------------------------------------------------------------------
def test_ErrorResolution():
    result = _Evaluate([_UPDATE_RULE])

    assert result.resolution == textwrap.dedent(
        f"""\
        1) Open the repository's [Rules settings](https://github.com/gt-csse/RepoAuditorWeb/settings/rules) page.
        2) Click the name of the ruleset that targets `main`.
        3) Clear the **Restrict updates** checkbox in the **Branch rules** section.
        4) Click the **Save changes** button at the bottom of the page.

        See [Available rules for rulesets]({_DOCUMENTATION_URL})
        for more information.
        """,
    )


# ----------------------------------------------------------------------
# The resolution directs the user to set the rule when updates must be restricted.
def test_ErrorResolutionWhenRequired():
    result = _Evaluate([], require=True)

    assert result.resolution == textwrap.dedent(
        f"""\
        1) Open the repository's [Rules settings](https://github.com/gt-csse/RepoAuditorWeb/settings/rules) page.
        2) Click the name of the ruleset that targets `main`.
        3) Check the **Restrict updates** checkbox in the **Branch rules** section.
        4) Click the **Save changes** button at the bottom of the page.

        See [Available rules for rulesets]({_DOCUMENTATION_URL})
        for more information.
        """,
    )


# ----------------------------------------------------------------------
# A ruleset may target a branch other than 'main', so the resolution names the branch that was
# queried.
def test_ResolutionUsesBranchName():
    result = _Evaluate([_UPDATE_RULE], branch="trunk")

    assert result.resolution is not None
    assert "`trunk`" in result.resolution
    assert "`main`" not in result.resolution


# ----------------------------------------------------------------------
# The settings url is derived from the repository under audit rather than hard-coded, so it points
# at an Enterprise host when one is being audited.
def test_ResolutionUsesEnterpriseUrl():
    result = _Evaluate([_UPDATE_RULE], url="https://github.example.com/my-org/my-repo")

    assert result.resolution is not None
    assert "(https://github.example.com/my-org/my-repo/settings/rules)" in result.resolution


# ----------------------------------------------------------------------
def test_Skip():
    requirement = RestrictUpdatesRequirement()

    result = requirement.Evaluate(_CreateModule(requirement), {}, {"skip": True, "require": False})

    assert result.result == EvaluateResultValue.Skipped
